[build]
	command = "npm run prod"
	publish = "dist"

[[headers]]
	for = "/*"
	[headers.values]
		Cache-Control = "no-cache"
		Permissions-Policy = """geolocation=(), midi=(), sync-xhr=(), microphone=(), camera=(),
		magnetometer=(), gyroscope=(), payment=()"""
		Referrer-Policy = "no-referrer"
		Report-To = """{"group": "default", "max_age":31536000,
		"endpoints": [{"url":"https://adilsonsantos.report-uri.com/a/d/g"}]}"""
		Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options = "nosniff"

[[headers]]
	for = "/"
	[headers.values]
		Content-Type = "text/html; charset=utf-8"
		Cache-Control = "no-cache"
		Content-Security-Policy = """default-src 'none'; script-src 'self';
		style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; font-src 'self';
		manifest-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self';
		object-src 'none'; frame-src 'self'; upgrade-insecure-requests;
		require-trusted-types-for 'script'; report-to 'default'"""
		Cross-Origin-Opener-Policy = "same-origin; report-to='default'"
		Cross-Origin-Embedder-Policy = "require-corp; report-to='default'"
		Cross-Origin-Resource-Policy = "same-site"
		X-XSS-Protection = "1; mode=block"

[[headers]]
	for = "/*.(apng|avif|bmp|ico|jpeg|jpg|png|svg|webp)"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
	for = "/*.(xml|txt)"
	[headers.values]
		Cache-Control = "public, max-age=172800"

[[headers]]
	for = "/*.woff2"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
	for = "/*.woff"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
	for = "/*.webmanifest"
	[headers.values]
		Cache-Control = "public, max-age=604800, immutable"
		Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
	for = "/*.js"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"
		Content-Type = "text/javascript; charset=utf-8"

[[headers]]
	for = "/*.css"
	[headers.values]
		Cache-Control = "public, max-age=31536000, immutable"
		Content-Type = "text/css; charset=utf-8"

[[redirects]]
	from = "/*"
	to = "/404.html"
	status = 404

[[redirects]]
	from = "http://adilsonsantos.netlify.app/*"
	to = "https://adilsonsantos.netlify.app/:splat"
	status = 301
	force = true

[[redirects]]
	from = "www.adilsonsantos.netlify.app/*"
	to = "https://adilsonsantos.netlify.app/:splat"
	status = 301
	force = true

