[build]
  command = "gulp build --prod"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"

  for = "/"
  [headers.values]
    Expect-CT = "max-age=2592000, report-uri=https://adilsonsantos.report-uri.com/r/d/ct/enforce"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; payment 'none'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    #Content-Security-Policy-Report-Only = "default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://adilsonsantos.report-uri.com/r/d/csp/wizard; report-to default"
    Report-To = """{"group":"default","max_age":31536000,"endpoints":[{"url":"https://adilsonsantos.report-uri.com/a/d/g"}],"include_subdomains":true}"""
    Content-Security-Policy = "default-src 'none'; script-src 'self' 'sha256-0A3SoNnOj/VD5rKtWDb4PSvN8Br+QRibbwlM+84okfY='; img-src 'self'; connect-src 'self'; font-src 'self';style-src 'self' 'sha256-1sdq/MR29ktsBcVbBpLu36j3tpYFN2Bx27FosjPE+w8=' 'sha256-KH2YwEdf//xSEFjlCpPbq5fP295fpX3FfX2ot/ID4bQ=' 'sha256-W3zpZZI4QLHfC0sQzOPHTTxgt0mV8RIKiCctivUo0uM=' 'sha256-CeOZdUQ3dX09k8BJSSwU6imjVp6wHX2AJK+mXCe8oyw='; manifest-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; object-src 'none'; upgrade-insecure-requests;  block-all-mixed-content; disown-opener; report-to default; report-uri 'https://adilsonsantos.report-uri.com/r/d/csp/enforce'; prefetch-src 'self'"

  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache"

  for = "*.(apng|bmp|css|ico|jpeg|jpg|js|png|svg|webp)"
  [headers.values]
    Cache-Control = "public, max-age=5184000, must-revalidate"

  for = "*.(xml|txt)"
  [headers.values]
    Cache-Control = "max-age=172800, public, must-revalidate"

  for = "*.(woff|woff2)"
  [headers.values]
    Cache-Control = "max-age=604800, public, must-revalidate"

  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "max-age=604800, public, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "http://adilsonsantos.netlify.com/*"
  to = "https://adilsonsantos.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "www.adilsonsantos.netlify.com/*"
  to = "https://adilsonsantos.netlify.com/:splat"
  status = 301
  force = true

[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = '–production'

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
